import numpy as np
import matplotlib.pyplot as plt

class chaos_game:
     
     
     """ A single chaos_game class creating a fractal, using ngon and
          an initial point selected at random inside it. """

     def __init__(self,n,r):
          
          
          """
          The class chaos_game takes 2 arugments
          Parameters:-
          n = Type:- integer. Value:- grater than or equal to 3
          r = Type:- float. Value:- between 0 and 1
        
          """          
          if type(n) != int and type(r) != float:
               raise TypeError("n must be integer and r must be float")
          
          if n >=3:
               self.n = n
          if 0 < r < 1:
               self.r = r
                    
                    
          else:
               raise ValueError("range out of index")

          self.corner = self._generate_ngon()


     def _generate_ngon(self):
          """ Computes the corners of ngon. """
          values = np.linspace(0,2*np.pi,self.n)
          corner=[(np.sin(thehta),np.cos(thehta)) for thehta in values]
          return corner

     def plot_ngon(self):
          """ plots the generated n-gon."""
          plt.scatter(*zip(*self.corner))
          plt.axis("equal")
          plt.axis("off")
          plt.show()

     def _starting_point(self):
          """ Picks a random point within the ngon """
          x=[];y=[]
          weight = np.random.random(self.n)
          for i in range(self.n):
               x+= [weight[i]/np.sum(weight)]
               y+= [np.array(self.corner[i]) * x[i]]
               
               
                       
          return sum(y)

     def iterate(self,steps, discard=5):
          """ Iterate number of steps and stores it as a list"""
          points=[]
          points.append(self._starting_point())
          for i in range(steps):
               j = np.array(self.corner)[np.random.randint(0,self.n)]
               points += [self.r*(points[i] + (1-self.r)*j)]              
          self.points = points

     def plot(self,color=False, cmap="jet"):
          """ plots figures that are generated by the iterature """
          if color:
               liste = []
               for i in self.corner:
                    liste.append(i)

               plt.scatter(*zip(*liste))
               plt.show()
               
          else:
               cmap = "black"

          plt.scatter(*zip(*self.points),marker='.',s = 0.1 ,c = cmap)
          plt.axis("equal")
          plt.axis("off")
          

          

     def show(self):
          """ calls the method plot and shows the plot"""
          self.plot(False,"jet")
          plt.show()
          
          
        

     def savepng(self,outfile,color=False, cmap="jet"):
          """ saving the figure as a png after calling the method plot"""
          
          if "." not in outfile: 
              name = outfile + ".png"
              
          elif ".png" in outfile:
               name = outfile
             
          elif outfile[:-4] != ".png":
             raise TypeError("must end with .png")


          
          self.plot()
          plt.savefig(name, dpi=300,transparent=True)
          
          
         

if __name__ == "__main__":
     """ Testing n_gons where n is between 3 & 8"""
     for i in range(3,9):
          cg = chaos_game(i,0.9)
          cg.plot_ngon()

         

     """ Generating figures and saving them as .png"""
     cg1 = chaos_game(4, float(1/3))
     cg1.iterate(10000)
     cg1.show()
     cg1.savepng("fig1")
     
    
     cg2 = chaos_game(5, float(1/3))
     cg2.iterate(10000)
     cg2.show()
     cg2.savepng("fig2")
     
     
         
     cg3 = chaos_game(5, float(3/8))
     cg3.iterate(10000)
     cg3.show()
     cg3.savepng("fig3")
     
     
     
     cg4 = chaos_game(6, float(1/3))
     cg4.iterate(10000)
     cg4.show()
     cg4.savepng("fig4")

     """ Testing the starting point"""
     pentagon=[]
     for i in range(10000):
          pentagon.append(cg4._starting_point())
     plt.scatter(*zip(*pentagon),marker='.', s=0.1)
     plt.axis('equal')
     plt.show()